Kafka replacement
Axway/amplify-integration-labs pull request #6
Opened 2024-10-24 08:18 UTC by DDigoin

Replacement of Kafka by RabbitMQ following the closure of the Upstash and CloudKarafka online services

2024-10-24 13:47 UTC, ThierryMa requested changes

2024-10-24 13:47 UTC, ThierryMa commented on asynchronous-integration/images/intro-integration2.jpg
add a label on frist step here please

2024-10-24 13:47 UTC, ThierryMa commented on asynchronous-integration/images/lab2-https-client-post-set-value.jpg
should we adapte the team message screeen to match this settings?

2024-10-29 09:09 UTC, DDigoin reviewed
I made changes

2024-10-29 09:09 UTC, closed without merging